// Generated by CoffeeScript 1.7.1
var Example, obj,
  __slice = [].slice;

Example = (function() {
  function Example(arg) {
    alert("Example made with " + arg);
  }

  Example.prototype.say_something = function() {
    var arg, args, _i, _len, _results;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    _results = [];
    for (_i = 0, _len = args.length; _i < _len; _i++) {
      arg = args[_i];
      _results.push(alert("An argument: " + arg));
    }
    return _results;
  };

  return Example;

})();

obj = new Example("Coffee");

obj.say_something("Hello", "World");
